### ISSUE TITLE
too many arguments

### ISSUE THREAD

**Issue by leone9898** [Aussiemon/ljd#2]
hello i tried to convert luajt languages to lua but show this error in cmd with administator mode why?

python "C:\luajit\main.py" "C:\luajit\AISowingCultivatorFix.lua" "C:\luajit\lua\AISowingCultivatorFix.lua"
Usage: main.py [options]

main.py: error: Too many arguments.

**Comment by Aussiemon** [comment]
You have to define the arguments:
`python "C:\luajit\main.py" -f "C:\luajit\AISowingCultivatorFix.lua" -o "C:\luajit\lua\AISowingCultivatorFix.lua"`
