### ISSUE TITLE
luac64 File operation with this suffix failed

### ISSUE THREAD

**Issue by etjson** [Aussiemon/ljd#5]
luac64 File operation with this suffix failed

```text
Unknown prototype flags: 11100000
Failed to read prototype
```

I upload the file here
[app_ui_bag_BagLayer.zip](https://github.com/Aussiemon/ljd/files/10029100/app_ui_bag_BagLayer.zip)

**Comment by Aussiemon** [comment]
It's not a normal LuaJIT file. This file or the author's version of LuaJIT has been modified in some unknown way, and won't be usable by LJD. Your best bet is to fork the code yourself and reverse-engineer the bytecode.
